services:
  backend:
    build: .
    image: elon-backend
    ports:
      - '3000:3000' # Maps host port 3000 to container port 3000
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - PORT=${PORT}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src:/app/src # Mount only src/ for development
      - ./prisma:/app/prisma # Mount only prisma/ for development
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    command: sh -c "npx prisma migrate deploy && npx tsx src/app.ts"

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=marc012345
      - POSTGRES_DB=elon
    volumes:
      - elon-pgdata:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - elon-redisdata:/data

volumes:
  elon-pgdata:
  elon-redisdata:
